apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cloud-cost-optimizer
spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: backend-sa

      containers:
        - name: backend
          image: 103533474179.dkr.ecr.us-east-1.amazonaws.com/cloud-cost-optimizer-backend:v2

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/cloud_cost_optimizer

            - name: AWS_DEFAULT_REGION
              value: us-east-1

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cloud-cost-optimizer

spec:
  selector:
    app: backend

  ports:
    - port: 8000
      targetPort: 8000

  type: ClusterIP