apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: cloud-cost-optimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: cloud_cost_optimizer
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: cloud-cost-optimizer
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP